version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    working_dir: /app
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/client
    environment:
      - NODE_ENV=development
    depends_on:
      - backend 